#!/bin/bash

#ddev-generated
## Description: Get aljibe config values. Special case for theme_path, where we get a list of theme paths without keys.
## Usage: aljibe-config [config_tag]
## Example: "ddev aljibe-config theme_path"
## Example: "ddev aljibe-config otherkey"

KEY=$1

CONFIG_FILE=".ddev/aljibe.yaml"
RETURN_KEYS=0

if [ ! -f $CONFIG_FILE ]; then
    echo "Aljibe config file not found"
    exit 1
fi

if [ -z "$KEY" ]; then
    echo "Please provide a config key"
    exit 1
fi


handle_options() {
  while [ $# -gt 0 ]; do
    case $1 in
      -k | --keys)
        RETURN_KEYS=1
        shift
        ;;
    esac
    shift
  done
}

# Main script execution
handle_options "$@"

readConfigFile () {
  ddev exec "yq -I=0 '.${1} // \"\"' /mnt/ddev_config/aljibe.yaml" || echo
}

TYPE=$(readConfigFile "$1 | kind")

readArray () {
  if [ $RETURN_KEYS -eq 1 ]; then
    while IFS= read -r key; do
      echo -n "$key" | sed 's/^- //'
    done < <(readConfigFile "$1 | keys")
  else
    while IFS= read -r theme_path; do
      echo -n "$theme_path"
    done < <(readConfigFile "$1[]")
  fi
}

readScalar () {
  readConfigFile "$1"
}

case $TYPE in
  "scalar")
    readScalar "$KEY"
    ;;
  "seq")
    readArray "$KEY"
    ;;
  "map")
    readArray "$KEY"
    ;;
  *)
    readScalar "$KEY"
    ;;
esac

