#!/bin/bash
#ddev-generated
## Description: Configure environment and optionally install sites
## Usage: setup [flags]
## Flags: [{"Name":"noinstall","Usage":"setup --noinstall"}]
## Example: ddev setup --noinstall

# Load environment variables
set -a
source .ddev/.env
set +a

# Initialize our own variables
NO_INSTALL=0
NO_THEMES=0

CONFIG_DEFAULT_SITE=$(ddev aljibe-config default_site)
if [ "$CONFIG_DEFAULT_SITE" == 'null' ]; then
  SITES=('self')
else
  SITES=("$CONFIG_DEFAULT_SITE")
fi
VERBOSE=0
THEMES=()

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

help() {
echo "Usage: $0 [options]"
  echo
  echo "Options:"
  echo "  -h, --help        Show this help message and exit"
  echo "  -n, --no-install  Do not install sites"
  echo "  -s, --sites       Install specific sites"
  echo "  -a, --all         Install all sites"
  echo "  -v, --verbose     Show verbose output"
  exit 0
}


has_argument() {
    [[ ("$1" == *=* && -n ${1#*=}) || ( ! -z "$2" && "$2" != -*)  ]];
}

extract_argument() {
  if [[ $1 == *=* ]]; then
    echo "${1#*=}"
  else
    echo "$2"
  fi
}

handle_options() {
  while [ $# -gt 0 ]; do
    case $1 in
      -a | --all)
        mapfile -t SITES < <(drush site:alias --fields=name --format=list --filter=.local | sed 's/@//' | sed 's/.local//')
        shift
        ;;
      -h | --help)
        help
        shift
        ;;
      -n | --no-install)
        NO_INSTALL=1
        shift
        ;;
      --no-themes)
        NO_THEMES=1
        shift
        ;;
      -s | --sites*)
        if [[ $1 == *=* ]]; then
          IFS=',' read -a SITES <<< "$(extract_argument "$1")"
          shift
        else
          if [ -z "$2" ]; then
            echo "Sites not specified." >&2
            exit 0
          fi
          IFS=',' read -a SITES <<< "$2"
          shift 2
        fi
        ;;
      -t | --themes*)
        if [[ $1 == *=* ]]; then
          IFS=',' read -a THEMES <<< "$(extract_argument "$1")"
          shift
        else
          if [ -z "$2" ]; then
            echo "Themes not specified." >&2
            exit 0
          fi
          IFS=',' read -a THEMES <<< "$2"
          shift 2
        fi
        ;;
      -v | --verbose)
        VERBOSE=1
        shift
        ;;
      *)
        echo "Invalid option: $1" >&2
        exit 0
        ;;
    esac
  done
}

# Main script execution
handle_options "$@"

# Initialice local environment
ddev composer install || exit 1
ddev exec vendor/bin/grumphp git:init

## Building frontend theme
if [ "$NO_THEMES" -eq 0 ]; then
  echo -e "\033[32m\n########################################################\n"
  echo -e "\033[32mBuilding frontend themes \n"
  echo -e "\033[32m########################################################\033[0m\n"
  if [ ${#THEMES[@]} -eq 0 ]; then
    readarray -t THEMES < <(ddev aljibe-config theme_paths_keys)
  fi

  if [ ${#THEMES[@]} -eq 0 ]; then
    echo "No themes found."
  else
     # Start the SPINNER in the background
    (SPINNER="/|\\-/|\\-"; while :; do for i in `seq 0 7`; do echo -n "${SPINNER:$i:1}"; echo -en "\010"; sleep 0.2; done; done) &
    SPINNER_PID=$!
    for theme in "${THEMES[@]}"; do
      echo -e "\033[32mBuilding theme:\033[32;1m ${theme}\033[0m"
      if [ $VERBOSE -eq 1 ]; then
        ddev frontend production "$theme"
      else
        ddev frontend production "$theme" &> /dev/null &
      fi
    done
  fi

  [ $VERBOSE -eq 0 ] && wait $!
  kill $SPINNER_PID > /dev/null 2>&1 && echo -e "\033[2K"
fi

ADDITIONAL_HOSTNAMES=""

# Check if --no-install option is not provided
if [ "$NO_INSTALL" -eq 0 ]; then
    for SITE in "${SITES[@]}"; do
        if [ "$ADDITIONAL_HOSTNAMES" != "default" ]; then
          if [ "$ADDITIONAL_HOSTNAMES" == "" ]; then
            ADDITIONAL_HOSTNAMES="${SITE}"
          else
            ADDITIONAL_HOSTNAMES="${ADDITIONAL_HOSTNAMES},${SITE}"
          fi
        fi
        echo -e "\033[32m\n########################################################\n"
        echo -e "\033[32mInstalling site:\033[32;1m ${SITE}\n"
        echo -e "\033[32;2m########################################################\033[0m\n"

        ddev site-install $SITE
    done
fi

if [ "$ADDITIONAL_HOSTNAMES" != "" ]; then
  echo "Make sure that you have those additional hostnames added to your .ddev/config.yml file:"
  echo "additional_hostnames: [${ADDITIONAL_HOSTNAMES}]"
fi
