#!/bin/bash
#ddev-generated
## Description: Configure environment and optionally install sites
## Usage: setup [flags]
## Flags: [{"Name":"noinstall","Usage":"setup --noinstall"}]
## Example: ddev setup --noinstall

# Load environment variables
set -a
source .ddev/.env
set +a

# Initialize our own variables
no_install=0

SITES=${DEFAULT_SITE:-'self'}

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.


has_argument() {
    [[ ("$1" == *=* && -n ${1#*=}) || ( ! -z "$2" && "$2" != -*)  ]];
}

extract_argument() {
  echo "${2:-${1#*=}}"
}

# Function to handle options and arguments
handle_options() {
  while [ $# -gt 0 ]; do
    case $1 in
      -n | --no-install)
        no_install=1
        shift
        ;;
      -s | --sites*)
        if ! has_argument "$@"; then
          echo "Site not specified." >&2
          exit 0
        fi
        echo
        IFS=',' read -a SITES <<< "$(extract_argument "$@")"
        shift
        ;;
      -a | --all)
        mapfile -t SITES < <(drush site:alias --fields=name --format=list --filter=.local | sed 's/@//' | sed 's/.local//')
        shift
        ;;
      *)
        echo "Invalid option: $1" >&2
        exit 0
        ;;
    esac
    shift
  done
}

# Main script execution
handle_options "$@"

# Initialice local environment
ddev composer install || exit 1
ddev exec vendor/bin/grumphp git:init

## Building frontend theme
echo -e "\033[32m\n########################################################\n"
echo -e "\033[32mBuilding frontend themes\n"
echo -e "\033[32m########################################################\033[0m\n"
readarray -t themes < <(ddev aljibe-config theme_paths_keys)
if [ ${#themes[@]} -eq 0 ]; then
  echo "No themes found."
  exit 0
fi
ddev aljibe-config theme_paths_keys | xargs ddev frontend production "$1"


ADDITIONAL_HOSTNAMES=""

# Check if --no-install option is not provided
if [ "$no_install" -eq 0 ]; then
    for SITE in "${SITES[@]}"; do
        if [ "$ADDITIONAL_HOSTNAMES" != "default" ]; then
          if [ "$ADDITIONAL_HOSTNAMES" == "" ]; then
            ADDITIONAL_HOSTNAMES="${SITE}"
          else
            ADDITIONAL_HOSTNAMES="${ADDITIONAL_HOSTNAMES},${SITE}"
          fi
        fi
        echo -e "\033[32m\n########################################################\n"
        echo -e "\033[32mInstalling site:\033[32;1m ${SITE}\n"
        echo -e "\033[32;2m########################################################\033[0m\n"

        ddev site-install $SITE
    done
fi

echo "Make sure that you have those additional hostnames added to your .ddev/config.yml file:"
echo "additional_hostnames: [${ADDITIONAL_HOSTNAMES}]"
