#!/bin/bash
#ddev-generated
## Description: Install given drupal site
## Usage: site-install
## Example: ddev site-install default
SITE_PROFILES_FILE=".ddev/site-profiles"
SITE=${1:-'default'}
ENV=${2:-'local'}
SITE_ALIAS=$SITE.$ENV
DRUPAL_PROFILE=""

if [ -f $SITE_PROFILES_FILE ]; then
  source  $SITE_PROFILES_FILE
else
  echo "No SITE_PROFILES_FILE found. If your site needs a custom profile, please create a $SITE_PROFILES_FILE file."
fi

cd  $DDEV_APPROOT || exit

## Check if drush alias for this site exists when drush @${SITE_ALIAS} return "could not be found"
if [ "$(drush @${SITE_ALIAS} status 2>&1 | grep 'could not be found')" ]; then
  echo "Drush alias for ${SITE} does not exist. Please create it first."
else
  SITE_PATH=$(ddev drush @${SITE_ALIAS} status --field=site)
  chmod u+w ${DDEV_DOCROOT}/${SITE_PATH} -R
  mkdir -p ${DDEV_DOCROOT}/${SITE_PATH}/files/behat/errors

  # Ensure that the settings.ddev.php file exists and is properly configured
  if [ "$SITE" != "default" ]; then
    # Remove dots and colons from the site name to make it a valid database name
    DBNAME=$(echo $SITE | sed 's/[^a-zA-Z0-9]//g')
    if [ ! -f ${DDEV_DOCROOT}/${SITE_PATH}/settings.ddev.php ]; then
      cp ${DDEV_DOCROOT}/sites/default/settings.ddev.php ${DDEV_DOCROOT}/${SITE_PATH}/settings.ddev.php
      sed -i "s/\['database'\] = \"db\"/\['database'\] = \"db_${DBNAME}\"/g" ${DDEV_DOCROOT}/${SITE_PATH}/settings.ddev.php
    fi
    echo "" | ddev import-db --database=db_${DBNAME} &> /dev/null
  fi
  cp ${DDEV_DOCROOT}/${SITE_PATH}/example.settings.local.php ${DDEV_DOCROOT}/${SITE_PATH}/settings.local.php
  cp ${DDEV_DOCROOT}/${SITE_PATH}/example.local.drush.yml ${DDEV_DOCROOT}/${SITE_PATH}/local.drush.yml

  ddev drush @${SITE_ALIAS} sql:drop -y
  # if $DRUPAL_PROFILE is not empty, then install the site with the given profile
  if [ ! -z "$DRUPAL_PROFILE" ]; then
    ddev drush @${SITE_ALIAS} site:install $DRUPAL_PROFILE --existing-config -y --sites-subdir=${SITE_PATH#sites/}
  else
    ddev drush @${SITE_ALIAS} site:install --existing-config -y --sites-subdir=${SITE_PATH#sites/}
  fi

  ddev drush @${SITE_ALIAS} cim -y
  ddev drush @${SITE_ALIAS} cr
  ddev drush @${SITE_ALIAS} uli
fi

