#ddev-generated
fail_on_hook_fail: True
hooks:
  pre-start:
   - exec-host: |
       if pip3 show PyYAML &>/dev/null; then
         ddev propagate-external-links
       else
         echo "[ERROR] Aljibe requires python with yaml extension."
       fi
