#!/bin/bash
#ddev-generated

## Check if a project is running. If it is not, start it.
star_project() {
  if [ "${DDEV_PROJECT_STATUS}" != "running" ] && [ -z "$no_recursion" ]; then
      echo "Project ${DDEV_PROJECT} is not running, starting it"
      ddev start
  fi
}

## Helps checking if there are arguments in the command
has_argument() {
  [[ ("$1" == *=* && -n ${1#*=}) || ( -n "$2" && "$2" != -*) ]];
}

## Extracts the argument from the command
extract_argument() {
  if [[ $1 == *=* ]]; then
    echo "${1#*=}"
  else
    echo "$2"
  fi
}

# Run commands from an array of commands
#   $@: commands to run
# Example: run_commands "echo 'Hello world'"
run_commands() {
  local CMDS=("$@")
  if [ ${#CMDS[@]} -gt 0 ]; then
    for cmd in "${CMDS[@]}"; do
      echo "- running $cmd ... "
      eval "$cmd"
    done
  fi
}

# Run hooks from the aljibe-config file
#   $1: hook name
# Example: run_hooks "pre-install"
run_hooks() {
  echo -e "\033[32mRunning $1 commands: \033[0m\n"
  readarray -t CMDS < <(ddev aljibe-config hooks.$1)
  run_commands "${CMDS[@]}"
}