#!/bin/bash
UNAMEINFO="$(uname -s)"
case "${UNAMEINFO}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    *)          machine=Linux;;
esac

d_sed_i () {
    if [ "$machine" = "Linux" ]; then
        # Linux sed supports -i without a backup extension
        sed -i "$@"
    else
        # MacOS sed requires a backup extension, so we use 'bak' as a placeholder
        sed -i bak "$@"
    fi
}

d_cp_rTf () {
    if [ "$machine" = "Linux" ]; then
        cp -rTf "$@"
    else
        # MacOS cp does not support -rTf, so we use -Rf instead
        cp -Rf "$@"
    fi
}
